---
layout: cv
title: Aaron Hyde's Resume
---
# Aaron Hyde
Economics Major Data Science Minor at BYU - Idaho


<div id="webaddress">
<a href="aaronhyde636@gmail.com">aaronhyde636@gmail.com</a>
| <a href="https://www.linkedin.com/in/aaron-m-hyde/">My LinkedIn page</a>
</div>


## Currently

Student at Brigham Young University - Idaho studying to major in economics with a minor in data science


## Education

January 2024 - July 2027
Brigham Young University - Idaho
Bachelor of Science in Economics | Data Science Minor
GPA: 3.77

### Skills Aquired:
 - R Studio
 - Python
 - Microsoft PowerBI
 - SQL
 - Microsoft Excel


### Important Classes
 - Intermediate Microeconomics
 - Intermediate Macroeconomics
 - Data Wrangling/Visualizations
 

## Occupations

`2024-present`
__Testing Center Proctor__ BYU-Idaho Testing Center at Rexburg, ID

- Analyze and record data on 100-150 exams which were taken throughout the day. 
- Assessed situations of cheating and acknowledge it to students in a calm and direct manner. 
- Exemplified customer service with stressful students taking exams.





<!-- ### Footer

Last updated: March 2026 -->